server:
  port: 12368
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/myschool
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


ribbon:
  ReadTimeout: 1000000
  ConnectTimeout: 1000000

jiankang:
  pingan:
    damu: H:\workspace\file

logging:
  level:
    com.example.damuMyschool.mapper: debug