server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/WorkSpace/IDEA_WorkSpace/springboot-eureka-test/configserverdemo/src/main/resources/properties
